name: .Tests

on:
  workflow_call:
    inputs:
      ### Required
      target:
        description: PR number, test or prod
        required: true
        type: string

env:
  DOMAIN: apps.silver.devops.gov.bc.ca
  PREFIX: ${{ github.event.repository.name }}-${{ inputs.target }}

jobs:
  e2e-tests:
    name: E2E
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        project: [chromium, Google Chrome, firefox, safari, Microsoft Edge]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Fix permissions
        run: sudo chown -R $USER:$USER frontend
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: |
          npm ci
      - run: npx @playwright/test install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./frontend
      - run: npx @playwright/test install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        working-directory: ./frontend

      - name: Run Tests
        env:
          E2E_BASE_URL: https://${{ github.event.repository.name }}-${{ inputs.target }}-frontend.${{ env.DOMAIN }}/
          CI: "true"
        run: |
          npx playwright test --project="${{ matrix.project }}" --reporter=html

      - uses: actions/upload-artifact@v4
        if: always()
        name: upload results
        env:
          PW_TEST_HTML_REPORT_OPEN: always
        with:
          name: playwright-report-${{ matrix.project }}
          path: "./frontend/playwright-report" # path from current folder
          retention-days: 7
