name: PR

on:
  pull_request:

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, frontend]
    timeout-minutes: 10
    steps:
      - uses: bcgov/action-builder-ghcr@v2.3.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')

  # https://github.com/bcgov/action-deployer-openshift
  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      tag: ${{ github.event.number }}
      release: ${{ github.event.number }}
      triggers: ('backend/' 'frontend/' 'migrations/' 'charts/' '.github/')
      params: |
        --set backend.pdb.enabled=false \
        --set frontend.pdb.enabled=false \
        --set global.amsURL=https://test.j200.gov.bc.ca/pub/ams/ \
        --set global.nrptiAPIURL=https://nrpti-api-f00029-prod.apps.silver.devops.gov.bc.ca \
        --set global.nrcedURL=https://nrced.gov.bc.ca \
        --set-string backend.env.omrrAuthzDocsFlag=true \

  tests:
    name: Tests
    if: needs.deploys.outputs.triggered == 'true'
    needs: [deploys]
    uses: ./.github/workflows/.tests.yml
    with:
      target: ${{ github.event.number }}
  results:
    name: PR Results
    needs: [builds, deploys, tests]
    if: always() && (!failure()) && (!cancelled())
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Success!"
