name: PR Validate

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

concurrency:
  # Cancel in progress for PR open and close, but not merge_group
  group: ${{ github.workflow }}-${{ github.event.number || github.event.merge_group.base_sha }}
  cancel-in-progress: true

jobs:
  # PR only, skip for merge_group
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: failure() && !success()
        run: |
          echo "Please use conventional commits in your PR title and re-run this job."
          echo "https://www.conventionalcommits.org/en/v1.0.0/"
          exit 1

  # PR only, skip for merge_group
  pr-description-add:
    name: PR Description Add
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      PREFIX: ${{ github.event.repository.name }}
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    timeout-minutes: 1
    steps:
      - uses: bcgov-nr/action-pr-description-add@v1.1.1
        with:
          add_markdown: |
            ---

            Thanks for the PR!

            Deployments, as required, will be available below:
            - [Frontend](https://${{ env.PREFIX }}-${{ github.event.number }}-frontend.${{ env.DOMAIN }})
            - [Backend](https://${{ env.PREFIX }}-${{ github.event.number }}-frontend.${{ env.DOMAIN }}/api/)

            Please create PRs in draft mode.  Mark as ready to enable:
            - [Analysis Workflow](https://github.com/${{ github.repository }}/actions/workflows/analysis.yml)

            After merge, new images are deployed in:
            - [Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge.yml)
