name: Soak Tests

on:
  schedule: [cron: "0 0/1 * * *"] # Every hour
  workflow_dispatch:
env:
  DOMAIN: apps.silver.devops.gov.bc.ca
  PREFIX: ${{ github.event.repository.name }}-${{ inputs.target }}
jobs:
  load-tests:
    name: Soak Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [ backend, frontend ]
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/k6-action@v0.3.1
        env:
          BACKEND_URL: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}/api
          FRONTEND_URL: https://${{ env.PREFIX }}-frontend.${{ env.DOMAIN }}
        with:
          filename: ./tests/load/${{ matrix.name }}-test.js
          flags: --vus 20 --duration 600s
